
"""CONSTANTS"""
# Text
FONT = "Arial"
SIZE = 12
COLOR = "black"

# Website text
WEB_TEXT = "Website: "
WEB_ROW = 2
WEB_COLUMN = 0 

# Email text
EMAIL_TEXT = "Email/Username: "
EMAIL_ROW = 3
EMAIL_COLUMN = 0

# Password text
PASS_TEXT = "Password: "
PASS_ROW = 4
PASS_COLUMN = 0

# Website entry
WEB_ENTRY_COLSPAN = 2
WEB_ENTRY_ROW = WEB_ROW
WEB_ENTRY_COLUMN = 1
WEB_ENTRY_WIDTH = 45

# Email entry
EMAIL_ENTRY_COLSPAN = 2
EMAIL_ENTRY_ROW = EMAIL_ROW
EMAIL_ENTRY_COLUMN = 1
EMAIL_ENTRY_WIDTH = WEB_ENTRY_WIDTH

# Password entry
PASS_ENTRY_COLSPAN = 1
PASS_ENTRY_ROW = PASS_ROW
PASS_ENTRY_COLUMN = 1
PASS_ENTRY_WIDTH = 26

# Add password button
ADDPASS_TEXT = "Add"
ADDPASS_ROW = 5
ADDPASS_COLUMN = 1
ADDPASS_COLSPAN = 2
ADDPASS_WIDTH = 38

# Generate random password button
RANDPASS_TEXT = "Generate password"
RANDPASS_ROW = PASS_ROW
RANDPASS_COLUMN = 2
RANDPASS_COLSPAN = 1
RANDPASS_WIDTH = 14

# Window
TITLE = "Password Manager"
PADX = 50
PADY = 30

# App Title
TITLE_FONT = FONT
TITLE_SIZE = 20
TITLE_ROW = 0
TITLE_COLUM = 0
TITLE_COLOR = "black"
TITLE_COLSPAN = 3


# Canvas
CANVAS_ROW = 1
CANVAS_COLUMN = 0
CANVAS_WIDTH = 120
CANVAS_HEIGHT = 120
CANVAS_COLSPAN = 3

# Image
IMAGE_PATH = "./cat.png"
IMAGE_X = CANVAS_WIDTH//2
IMAGE_Y = CANVAS_HEIGHT//2

